### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Configuration Manager
  description: Microsoft System Center 2012 R2 Configuration Manager suit la politique de cycle de vie fixe.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: b9a1c0fa5804c5929f39f72816e86e49c739d281
  ms.sourcegitcommit: 8465b0fa45ee2c451d1f1eaf7be9a1544cdad17f
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 03/12/2021
  ms.locfileid: "1462904"
name: Microsoft System Center 2012 R2 Configuration Manager
summary: >+
  Microsoft System Center 2012 R2 Configuration Manager suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Liens \n* [Politique du Service Pack](/lifecycle/policies/fixed#service-packs)\n* [Documentation pour Configuration Manager](/mem/configmgr/core/misc/online-documentation)\n* [Conseils en matière de migration](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
