### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops suit la politique de cycle de vie fixe.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: "Microsoft Application Virtualization Hosting 4.6 for Windows Desktops suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).\n\nCela concerne les éditions suivantes\_: for Windows Desktops\n\n"
products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Liens 
  * [Informations sur les produits et les migrations](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Politique du Service Pack](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Étant donné que le client App-V 4.6 utilise le serveur App-V 4.5, le serveur App-V 4.5 continuera d’être pris en charge selon les dates du cycle de vie d’App-V 4.6 lorsqu’il est utilisé avec le client App-V 4.6 pris en charge.

  ## <a name="editions"></a>Éditions 
  * pour les bureaux Windows