### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops suit la politique de cycle de vie fixe.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: "Microsoft Application Virtualization Hosting 5.1 for Windows Desktops suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).\n\nCela concerne les éditions suivantes\_: for Windows Desktops\n\n"
products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Liens 
  * [Informations sur le produit](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Éditions 
  * pour les bureaux Windows