### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security suit la stratégie de cycle de vie fixe.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908720"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security suit la stratégie de cycle de vie [fixe](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Liens \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security a été abandonné. L’assistance prend fin le 14 juillet 2015. Les mises à jour de définitions contre les programmes malveillants et les logiciels anti-espion ne seront plus disponibles après la fin de la prise en charge de la version du produit. Veuillez évaluer System Center Endpoint Protection en remplacement."
