### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security suit la politique de cycle de vie fixe.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Liens 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security a été interrompu le 14 juillet 2015. Les mises à jour de définition Antimalware et Antispyware ne seront plus disponibles après la fin du support de la version produit. Veuillez évaluer System Center Endpoint Protection comme remplacement.