### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security suit la politique de cycle de vie fixe.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113406"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Liens \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security a été interrompu le 14 juillet 2015. Les mises à jour de définition Antimalware et Antispyware ne seront plus disponibles après la fin du support de la version produit. Veuillez évaluer System Center Endpoint Protection comme remplacement."
