### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 suit la politique de cycle de vie fixe.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "816050"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > Le support de ce produit a pris fin. Voir les conseils de migration ci-dessous.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Liens \n* [Conseils en matière de migration](/mem/configmgr/core/migration/planning-for-migration)\n* [Conseils supplémentaires concernant la migration](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
