### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Microsoft Application Virtualization 5.1 suit la politique de cycle de vie fixe.
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  Microsoft Application Virtualization 5.1 suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).

  Cela s’applique aux éditions suivantes : pour les services Bureau à distance, pour les Bureaux Windows

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Liens 
  * [Informations sur le produit](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Éditions 
  * pour les services Bureau à distance
  * pour les bureaux Windows