### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 suit la politique de cycle de vie fixe.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137419"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > Le support de ce produit a pris fin. Voir les conseils de migration ci-dessous.
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Liens \n* [Conseils en matière de migration](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Conseils supplémentaires concernant la migration](/mem/configmgr/core/migration/planning-for-migration)"
