### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4,6 pour les ordinateurs de bureau Windows
  description: Microsoft Application Virtualization Hosting 4,6 for Windows Desktops suit la stratégie de cycle de vie fixe.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "816168"
name: Microsoft Application Virtualization Hosting 4,6 pour les ordinateurs de bureau Windows
summary: >+
  Microsoft Application Virtualization Hosting 4,6 for Windows Desktops suit la stratégie de cycle de vie [fixe](/lifecycle/policies/fixed) .


  Cela s’applique aux éditions suivantes : pour les ordinateurs de bureau Windows

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Liens \n* [Informations sur les produits et la migration](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Stratégie de Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Étant donné que le client App-V 4,6 utilise le serveur App-V 4,5, le serveur App-V 4,5 continuera d’être pris en charge en fonction des dates de cycle de vie d’App-V 4,6 lorsqu’il est utilisé avec le client App-V 4,6 pris en charge.\n\n## <a name=\"editions\"></a>Premium \n* pour les ordinateurs de bureau Windows"
