### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 suit la politique de cycle de vie fixe.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 suit la politique de cycle de vie [fixe](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > Le support de ce produit a pris fin. Voir les conseils de migration ci-dessous.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Liens 
  * [Conseils en matière de migration](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Conseils supplémentaires concernant la migration](/mem/configmgr/core/migration/planning-for-migration)