### YamlMime:Lifecycle
metadata:
  title: Virtualisation d’applications SoftGrid
  description: La virtualisation d’applications SoftGrid suit la stratégie de cycle de vie fixe.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "815470"
name: Virtualisation d’applications SoftGrid
summary: >
  La virtualisation d’applications SoftGrid suit la stratégie de cycle de vie [fixe](/lifecycle/policies/fixed) .


  Cela s’applique aux éditions suivantes : 4,1 pour les ordinateurs de bureau, 4,2 pour les ordinateurs de bureau, pour les services Terminal Server 4,1


  > [!IMPORTANT]

  > La prise en charge s’est terminée. Consultez les conseils de migration ci-dessous.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Liens \n* [Conseils de migration](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Premium \n* 4,1 pour les ordinateurs de bureau\n* 4,2 pour les ordinateurs de bureau\n* pour les services Terminal Server 4,1"
